# name: gcp-main
# on:
#   push:
#     branches:
#       - main
      
# jobs:
#   gcp-dev:
#     name: Build and Push to GCP
#     runs-on: ubuntu-latest

    

#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2
    
#     # Authenticate to Google Cloud using workload identity federation
#     - id: "auth"
#       name: "Obtain access token by using workload identity federation"
#       uses: "google-github-actions/auth@v1"

#       with:
#           # create_credentials_file: true
#           # token_format: access_token
#           workload_identity_provider: projects/796292922550/locations/global/workloadIdentityPools/confixa-github-actions/providers/congfixa-github-actions
#           service_account: github-action@confixa-rnd.iam.gserviceaccount.com

#     # - name: Authenticate with Google Cloud
#     #   uses: google-github-actions/auth@v0
#     #   with:
#     #     credentials: 0c828502b577634ea7436809a43a3e14a4a04e5a
                  
#     - name: Connect to Artifact Registry
#       run: |-
#           gcloud auth configure-docker --quiet
#           gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet
#           # echo ${{ steps.auth.outputs.access_token }} | docker login -u oauth2accesstoken --password-stdin https://asia-south1-docker.pkg.dev

#     - name: Build Docker Image
#       run: docker build -t asia-south1-docker.pkg.dev/confixa-rnd/confixa-docker-images/abc:$GITHUB_REF_NAME-$GITHUB_SHA .

#     - uses: actions/checkout@v2
#     - name: Set env
#       run: echo "GITHUB_BRANCH=$(echo $GITHUB_REF_NAME-$GITHUB_SHA)" >> $GITHUB_ENV

#     - name: Push Docker Image to Artifact Registry
#       run: |-
#         docker push asia-south1-docker.pkg.dev/confixa-rnd/confixa-docker-images/abc:$GITHUB_REF_NAME-$GITHUB_SHA

name: Push to GCP

on:
  push:
    branches:
    - 'main'

permissions:
    id-token: write
    contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: confixa-rnd
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: confixa-rnd
      run: |
        gcloud auth configure-docker asia-south1-docker.pkg.dev
        docker build -t asia-south1-docker.pkg.dev/confixa-rnd/confixa-docker-images/abc:latest .
        docker push asia-south1-docker.pkg.dev/confixa-rnd/confixa-docker-images/abc:latest
  
